//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane
    {
        public Dane()
        {
            this.Uzytkownicy = new HashSet<Uzytkownicy>();
        }
    
        public int ID { get; set; }
        public string Imie { get; set; }
        public string Rocznik { get; set; }
        public string Plec { get; set; }
        public string Waga { get; set; }
    
        public virtual ICollection<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
