//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane
    {
        public Dane()
        {
            this.Historia_Danych = new HashSet<Historia_Danych>();
            this.Uzytkownicy = new HashSet<Uzytkownicy>();
        }
    
        public int ID { get; set; }
        public string Imie { get; set; }
        public Nullable<int> Wiek { get; set; }
        public string Plec { get; set; }
        public Nullable<double> Waga { get; set; }
        public Nullable<double> Wzrost { get; set; }
        public Nullable<double> Obwod_Pasa { get; set; }
        public Nullable<double> Obwod_Bioder { get; set; }
        public Nullable<double> Zapotrzebowanie { get; set; }
    
        public virtual ICollection<Historia_Danych> Historia_Danych { get; set; }
        public virtual ICollection<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
