//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class DzienTreningowy
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Cwiczenie { get; set; }
        public Nullable<int> Czas { get; set; }
        public int ID_Treningu { get; set; }
    
        public virtual Treningi Treningi { get; set; }
    }
}
