//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public Nullable<double> Bialko { get; set; }
        public Nullable<double> Tluszcze { get; set; }
        public Nullable<double> Węglodowany { get; set; }
        public Nullable<double> Wartosc_Energetyczna { get; set; }
        public int ID_Kategori { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
    }
}
