//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spozycie
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<double> Bialko { get; set; }
        public Nullable<double> Weglowodany { get; set; }
        public Nullable<double> Tluszcz { get; set; }
        public Nullable<double> Kalorie { get; set; }
        public int ID_Diety { get; set; }
    
        public virtual Diety Diety { get; set; }
    }
}
