//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplementy
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Dawkowanie { get; set; }
        public string Dzialanie { get; set; }
    }
}
