//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treningi
    {
        public Treningi()
        {
            this.DzienTreningowy = new HashSet<DzienTreningowy>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Data_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
        public Nullable<int> Srednia_Dzienna { get; set; }
        public Nullable<int> Czas_Tydzien { get; set; }
        public Nullable<int> Ilosc_Tydzien { get; set; }
        public string Czestotliwosc { get; set; }
        public int ID_Uzytkownika { get; set; }
    
        public virtual ICollection<DzienTreningowy> DzienTreningowy { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
